---

- name: Install AD Domain services
  win_feature:
   name: AD-Domain-Services
   state: present

- name: Setup AD Controller
  win_domain:
   dns_domain_name: "{{ad_domain_name}}"
   safe_mode_password: "{{ad_safe_mode_passwd}}"

- name: Reboot the instance post configuration
  win_reboot:

- name: Print the domain list
  win_shell: 'nltest /dclist:"{{ ad_domain_name }}"'
  register: domain_list

- debug:
   var: domain_list

